@extends('layouts.app')

@section('title', 'Generate Number PF')

@section('content')
    <div class="narrow">
        <h1>Generate Number PF</h1>
        <p class="muted">Only Project Name is required (<span class="req">*</span>). The PF number is generated by the server when you submit.</p>

        <form method="POST" action="{{ route('pf.store') }}" class="card" data-submit-once>
            @csrf
            <input type="hidden" name="submission_token" value="{{ $token }}">

            <div class="field">
                <label for="project_name">Project Name <span class="req">*</span></label>
                <input id="project_name" name="project_name" type="text" value="{{ old('project_name') }}" maxlength="255"
                       required autofocus autocomplete="off" @error('project_name') class="is-invalid" @enderror>
            </div>

            <div class="field">
                <label for="sf_number">SF Number</label>
                <input id="sf_number" name="sf_number" type="text" value="{{ old('sf_number') }}" maxlength="100"
                       autocomplete="off" @error('sf_number') class="is-invalid" @enderror>
                <div class="hint">Optional. Reference to an existing SF.</div>
            </div>

            <div class="field">
                <label for="vnid">VNID</label>
                <input id="vnid" name="vnid" type="text" value="{{ old('vnid') }}" maxlength="100"
                       autocomplete="off" @error('vnid') class="is-invalid" @enderror>
                <div class="hint">Optional.</div>
            </div>

            <div class="field">
                <label for="customer_name">Customer Name</label>
                <input id="customer_name" name="customer_name" type="text" value="{{ old('customer_name') }}" maxlength="255"
                       autocomplete="off" @error('customer_name') class="is-invalid" @enderror>
                <div class="hint">Optional.</div>
            </div>

            <button type="submit" class="btn btn-primary">Generate PF Number</button>
        </form>
    </div>
@endsection
