@extends('layouts.app')

@section('title', 'Generate Number SF')

@section('content')
    <div class="narrow">
        <h1>Generate Number SF</h1>
        <p class="muted">Fields marked with <span class="req">*</span> are required. The SF number is generated by the server when you submit.</p>

        <form method="POST" action="{{ route('sf.store') }}" class="card" data-submit-once>
            @csrf
            <input type="hidden" name="submission_token" value="{{ $token }}">

            <div class="field">
                <label for="vnid">VNID <span class="req">*</span></label>
                <input id="vnid" name="vnid" type="text" value="{{ old('vnid') }}" maxlength="100"
                       required autofocus autocomplete="off" @error('vnid') class="is-invalid" @enderror>
            </div>

            <div class="field">
                <label for="customer_name">Customer Name <span class="req">*</span></label>
                <input id="customer_name" name="customer_name" type="text" value="{{ old('customer_name') }}" maxlength="255"
                       required autocomplete="off" @error('customer_name') class="is-invalid" @enderror>
            </div>

            <div class="field">
                <label for="service">Service <span class="req">*</span></label>
                <input id="service" name="service" type="text" value="{{ old('service') }}" maxlength="255"
                       required autocomplete="off" @error('service') class="is-invalid" @enderror>
            </div>

            <button type="submit" class="btn btn-primary">Generate SF Number</button>
        </form>
    </div>
@endsection
